name: myptv
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - pandas
  - pip
  - pytest
  - setuptools
  - six
  - wheel
  - imageio
  - numpy
  - scikit-image
  - scipy
  - pyyaml
  - pillow >=9.5.0
  - tk
  - multiprocessing
